title: GSA Minecraft Wiki
description: GSA Minecraft Wiki
baseurl: "" # Leave empty for personal site
url: "https://fluttercat555.github.io/gsa-mc-wiki/"

theme: minima

# Enable dark mode
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
